<option value="ccc">all community
</option><option value="eee">all event
</option><option value="sss" selected="selected">all for sale / wanted
</option><option disabled="" value="">--
</option><option value="ata"> antiques
</option><option value="atd"> antiques - by dealer
</option><option value="atq"> antiques - by owner
</option><option value="ppa"> appliances
</option><option value="ppd"> appliances - by dealer
</option><option value="app"> appliances - by owner
</option><option value="ard"> arts &amp; crafts - by dealer
</option><option value="art"> arts &amp; crafts - by owner
</option><option value="ara"> arts+crafts
</option><option value="pta"> auto parts
</option><option value="ptd"> auto parts - by dealer
</option><option value="pts"> auto parts - by owner
</option><option value="bad"> baby &amp; kid stuff - by dealer
</option><option value="bab"> baby &amp; kid stuff - by owner
</option><option value="baa"> baby+kids
</option><option value="bar"> barter
</option><option value="haa"> beauty+hlth
</option><option value="bid"> bicycles - by dealer
</option><option value="bik"> bicycles - by owner
</option><option value="bia"> bikes
</option><option value="boo"> boats
</option><option value="bod"> boats - by dealer
</option><option value="boa"> boats - by owner
</option><option value="bka"> books
</option><option value="bkd"> books &amp; magazines - by dealer
</option><option value="bks"> books &amp; magazines - by owner
</option><option value="bfa"> business
</option><option value="bfd"> business/commercial - by dealer
</option><option value="bfs"> business/commercial - by owner
</option><option value="ctd"> cars &amp; trucks - by dealer
</option><option value="cto"> cars &amp; trucks - by owner
</option><option value="cta"> cars+trucks
</option><option value="emq"> cds / dvds / vhs - by dealer
</option><option value="emd"> cds / dvds / vhs - by owner
</option><option value="ema"> cds/dvd/vhs
</option><option value="moa"> cell phones
</option><option value="mod"> cell phones - by dealer
</option><option value="mob"> cell phones - by owner
</option><option value="cla"> clothes+acc
</option><option value="cld"> clothing &amp; accessories - by deal
</option><option value="clo"> clothing &amp; accessories - by owne
</option><option value="cba"> collectibles
</option><option value="cbd"> collectibles - by dealer
</option><option value="clt"> collectibles - by owner
</option><option value="sya"> computers
</option><option value="syd"> computers - by dealer
</option><option value="sys"> computers - by owner
</option><option value="ela"> electronics
</option><option value="eld"> electronics - by dealer
</option><option value="ele"> electronics - by owner
</option><option value="grq"> farm &amp; garden - by dealer
</option><option value="grd"> farm &amp; garden - by owner
</option><option value="gra"> farm+garden
</option><option value="ssq"> for sale by dealer
</option><option value="sso"> for sale by owner
</option><option value="zip"> free stuff
</option><option value="fua"> furniture
</option><option value="fud"> furniture - by dealer
</option><option value="fuo"> furniture - by owner
</option><option value="gms"> garage sales
</option><option value="foa"> general
</option><option value="fod"> general for sale - by dealer
</option><option value="for"> general for sale - by owner
</option><option value="had"> health and beauty - by dealer
</option><option value="hab"> health and beauty - by owner
</option><option value="hsa"> household
</option><option value="hsd"> household items - by dealer
</option><option value="hsh"> household items - by owner
</option><option value="wan"> items wanted
</option><option value="jwa"> jewelry
</option><option value="jwd"> jewelry - by dealer
</option><option value="jwl"> jewelry - by owner
</option><option value="maa"> materials
</option><option value="mad"> materials - by dealer
</option><option value="mat"> materials - by owner
</option><option value="mca"> motorcycles
</option><option value="mcd"> motorcycles/scooters - by dealer
</option><option value="mcy"> motorcycles/scooters - by owner
</option><option value="msa"> music instr
</option><option value="msd"> musical instruments - by dealer
</option><option value="msg"> musical instruments - by owner
</option><option value="pha"> photo+video
</option><option value="phd"> photo/video - by dealer
</option><option value="pho"> photo/video - by owner
</option><option value="rva"> recreational vehicles
</option><option value="rvd"> rvs - by dealer
</option><option value="rvs"> rvs - by owner
</option><option value="sga"> sporting
</option><option value="sgd"> sporting goods - by dealer
</option><option value="spo"> sporting goods - by owner
</option><option value="tia"> tickets
</option><option value="tid"> tickets - by dealer
</option><option value="tix"> tickets - by owner
</option><option value="tla"> tools
</option><option value="tld"> tools - by dealer
</option><option value="tls"> tools - by owner
</option><option value="tad"> toys &amp; games - by dealer
</option><option value="tag"> toys &amp; games - by owner
</option><option value="taa"> toys+games
</option><option value="vga"> video gaming
</option><option value="vgd"> video gaming - by dealer
</option><option value="vgm"> video gaming - by owner
</option><option disabled="" value="">--
</option><option value="ggg">all gigs
</option><option value="hhh">all housing
</option><option value="jjj">all jobs
</option><option value="ppp">all personals
</option><option value="res">all resume
</option><option value="bbb">all services offered
</option>